"""Generate the python bindings of the XML schemas with xsdata.

`libsbgnpy.sbgn` and `libsbgnpy.render` are generated from
`src/libsbgnpy/schema/SBGN.xsd` (which imports `render.xsd`) with
[xsdata](https://github.com/tefra/xsdata). This script is the single source of
truth for the generation, it applies every step which used to be done by hand:

1. the documentation of the schema is html (`<p>`, `<ul>`, `<li>`, `<a>`), it is
   converted into plain text on a temporary copy of the schema, otherwise xsdata
   copies the markup with namespace prefixes into the docstrings,
2. xsdata generates google style docstrings (the convention of the package),
3. the module docstrings are added,
4. in `render.py` the namespace of the attributes is commented out: the schema
   declares them globally (`<xs:attribute ref="render:id"/>`), which makes them
   namespace qualified, but documents written by the SBGN tools carry them
   without a namespace,
5. `ruff format` and `ruff check --fix` bring the code on the style of the
   package.

Regenerate the bindings after a change of the schemas or of xsdata:

```bash
uv run python scripts/generate_bindings.py
```

`--check` generates into a temporary directory and fails if the committed
bindings differ, `tests/test_bindings.py` runs it.
"""

import argparse
import difflib
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from lxml import etree

REPO_DIR: Path = Path(__file__).parent.parent
PACKAGE_DIR: Path = REPO_DIR / "src" / "libsbgnpy"
SCHEMA_DIR: Path = PACKAGE_DIR / "schema"
SCHEMAS: tuple[str, ...] = ("SBGN.xsd", "render.xsd")
MODULES: tuple[str, ...] = ("sbgn.py", "render.py")

XSD_NS = "http://www.w3.org/2001/XMLSchema"
RENDER_NS = "http://www.sbml.org/sbml/level3/version1/render/version1"

MODULE_DOCSTRINGS: dict[str, str] = {
    "sbgn.py": '''"""Python bindings of the SBGN-ML schema.

Generated from `libsbgnpy/schema/SBGN.xsd` with
[xsdata](https://github.com/tefra/xsdata) by `scripts/generate_bindings.py`, see
`libsbgnpy/schema/README.md`; do not edit by hand. The classes mirror the
schema, so the
[SBGN specifications](https://sbgn.github.io/specifications)
are the reference for what an element means, and the docstrings are the
documentation of the schema.

An SBGN document is an `Sbgn` holding `Map` objects, a map holds `Glyph` and
`Arc` objects, and every element inherits from `Sbgnbase`, which carries the
`notes` and the `extension`. See the user guide for how they are used.
"""
''',
    "render.py": '''"""Python bindings of the render extension used by SBGN-ML.

Generated from `libsbgnpy/schema/render.xsd` with
[xsdata](https://github.com/tefra/xsdata) by `scripts/generate_bindings.py`, see
`libsbgnpy/schema/README.md`; do not edit by hand.

Render information colours a map. It is not part of the SBGN-ML schema: a
`RenderInformation` document is stored as an extension of the map, using the
vocabulary of the
[SBML render extension](https://sbml.org/documents/specifications/level-3/version-1/render/).
"""
''',
}

# the namespace entry following `"type": "Attribute"` in the field metadata
ATTRIBUTE_NAMESPACE = re.compile(
    r'(?P<type>"type": "Attribute",\n\s*)"namespace": "' + re.escape(RENDER_NS) + '"'
)


def plain_text(documentation: etree._Element) -> str:
    """Convert the html of an `xsd:documentation` into plain text.

    xsdata wraps the description of a docstring into a single paragraph, so the
    structure of the html (paragraphs, lists) is dropped and only its text kept.

    Args:
        documentation: the `xsd:documentation` element.

    Returns:
        The text of the documentation, whitespace collapsed.
    """
    text = etree.tostring(
        documentation, method="text", encoding="unicode", with_tail=False
    )
    return " ".join(text.split())


def prepare_schemas(target_dir: Path) -> Path:
    """Copy the schemas and convert their documentation into plain text.

    Args:
        target_dir: directory the schemas are written to.

    Returns:
        Path of the SBGN schema in the target directory.
    """
    for name in SCHEMAS:
        tree = etree.parse(SCHEMA_DIR / name)
        for documentation in tree.iter(f"{{{XSD_NS}}}documentation"):
            text = plain_text(documentation)
            for child in list(documentation):
                documentation.remove(child)
            documentation.text = text
        tree.write(target_dir / name, xml_declaration=True, encoding="UTF-8")
    return target_dir / "SBGN.xsd"


def postprocess(name: str, code: str) -> str:
    """Apply the fixes to a generated module.

    Args:
        name: file name of the module.
        code: code generated by xsdata.

    Returns:
        The fixed code, not yet formatted.
    """
    if name == "render.py":
        code = ATTRIBUTE_NAMESPACE.sub(
            r'\g<type># "namespace": "' + RENDER_NS + '"', code
        )
    return MODULE_DOCSTRINGS[name] + "\n" + code


def generate(output_dir: Path) -> None:
    """Generate the formatted binding modules into a directory.

    Args:
        output_dir: directory the modules are written to.
    """
    with tempfile.TemporaryDirectory() as tmp:
        work_dir = Path(tmp)
        schema_path = prepare_schemas(work_dir)
        subprocess.run(
            [
                sys.executable,
                "-m",
                "xsdata",
                "generate",
                schema_path.name,
                "--package",
                "generated",
                "--docstring-style",
                "Google",
                "--max-line-length",
                "88",
            ],
            cwd=work_dir,
            check=True,
            capture_output=True,
        )
        for name in MODULES:
            code = (work_dir / "generated" / name).read_text(encoding="utf-8")
            (output_dir / name).write_text(postprocess(name, code), encoding="utf-8")

    paths = [str(output_dir / name) for name in MODULES]
    # the configuration of the repository, also for files outside of it; its
    # per-file-ignores do not match the temporary directory, so `D` is ignored here
    config = ["--config", str(REPO_DIR / ".ruff.toml")]
    ruff = [sys.executable, "-m", "ruff"]
    subprocess.run(
        [*ruff, "check", "--fix", "-q", "--ignore", "D", *config, *paths], check=True
    )
    subprocess.run([*ruff, "format", "-q", *config, *paths], check=True)


def check() -> bool:
    """Compare freshly generated bindings with the committed ones.

    Returns:
        True if the committed bindings are up to date.
    """
    with tempfile.TemporaryDirectory() as tmp:
        output_dir = Path(tmp)
        generate(output_dir)
        up_to_date = True
        for name in MODULES:
            committed = (PACKAGE_DIR / name).read_text(encoding="utf-8").splitlines()
            generated = (output_dir / name).read_text(encoding="utf-8").splitlines()
            diff = list(
                difflib.unified_diff(
                    committed,
                    generated,
                    f"committed/{name}",
                    f"generated/{name}",
                    lineterm="",
                )
            )
            if diff:
                up_to_date = False
                print("\n".join(diff[:50]))
    return up_to_date


def main() -> int:
    """Run the generation, or the check with `--check`.

    Returns:
        The exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed bindings differ from freshly generated ones",
    )
    args = parser.parse_args()
    if args.check:
        if check():
            return 0
        print("bindings are outdated, run `python scripts/generate_bindings.py`")
        return 1

    with tempfile.TemporaryDirectory() as tmp:
        generate(Path(tmp))
        for name in MODULES:
            shutil.copyfile(Path(tmp) / name, PACKAGE_DIR / name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
